### PR TITLE
[#69] Fix: Base64URL valid characters are not properly validated

### LINKED ISSUE #69: Base64URL valid characters are not properly validated
reported https://github.com/Electric-Coin-Company/zashi-ios/issues/1420 here

### PR DESCRIPTION
**Pull request by pacu**
as reported by @daira Base64URL character set was not being enforced when creating a MemoBytes value from a supposedly base64URL.

This PR introduces such validation and tests that exercise that logic
closes #69

### CODE REVIEW

File: Sources/ZcashPaymentURI/Model.swift [hunk 1]
```diff
@@ -106,7 +107,17 @@ public struct MemoBytes: Equatable {
         self.data = memoStringData
     }
 
+    /// Initializes a [`MemoBytes`] from a [RFC 4648   Base64URL](https://datatracker.ietf.org/doc/html/rfc4648#section-5)
```
Comment (daira) [inline Sources/ZcashPaymentURI/Model.swift:110]:
```suggestion
    /// Initializes a [`MemoBytes`] from an [RFC-4648 Base64URL](https://datatracker.ietf.org/doc/html/rfc4648#section-5)
```

File: Sources/ZcashPaymentURI/Model.swift [hunk 2]
```diff
@@ -251,4 +262,12 @@ extension CharacterSet {
                 "}"
             )
         )
+
+    /// [RFC 4648  Base64URL](https://www.rfc-editor.org/rfc/rfc4648.html#section-5) Character Set.
```
Comment (daira) [inline Sources/ZcashPaymentURI/Model.swift:266]:
```suggestion
    /// [RFC-4648 Base64URL](https://www.rfc-editor.org/rfc/rfc4648.html#section-5) Character Set.
```

File: Tests/ZcashPaymentURITests/MemoBytesTests.swift [hunk 3]
```diff
@@ -58,4 +58,10 @@ final class MemoBytesTests: XCTestCase {
         
         XCTAssertThrowsError(try MemoBytes(bytes: [UInt8](repeating: 0xf4, count: 513)))
     }
+
+    func testInitWithInvalidTextFails() throws {
+        let invalidCharactersMemo = "QTw+Qg"
+
+        XCTAssertThrowsError(try MemoBytes(base64URL: invalidCharactersMemo))
+    }
```
Comment (daira) [inline Tests/ZcashPaymentURITests/MemoBytesTests.swift:66]: Add a test that uses all of the Base64URL characters (it should go with the other tests of success cases):
```swift
    /// Cross-check with Python's ``base64`` module using all Base64URL characters.
    /// ```python
    /// from base64 import b64decode, b64encode
    /// s = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"
    /// e = bytes([
    ///      0x00, 0x10, 0x83, 0x10, 0x51, 0x87, 0x20, 0x92, 0x8b, 0x30, 0xd3, 0x8f, 0x41, 0x14, 0x93, 0x51,
    ///      0x55, 0x97, 0x61, 0x96, 0x9b, 0x71, 0xd7, 0x9f, 0x82, 0x18, 0xa3, 0x92, 0x59, 0xa7, 0xa2, 0x9a,
    ///      0xab, 0xb2, 0xdb, 0xaf, 0xc3, 0x1c, 0xb3, 0xd3, 0x5d, 0xb7, 0xe3, 0x9e, 0xbb, 0xf3, 0xdf, 0xbf
    /// ])
    /// assert b64decode(s, altchars=b"-_") == e
    /// assert b64encode(e, altchars=b"-_") == s
    /// ```
    func testRoundTripWithAllBase64URLCharacters() {
        let s = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"
        let e: [UInt8] = [
            0x00, 0x10, 0x83, 0x10, 0x51, 0x87, 0x20, 0x92, 0x8b, 0x30, 0xd3, 0x8f, 0x41, 0x14, 0x93, 0x51,
            0x55, 0x97, 0x61, 0x96, 0x9b, 0x71, 0xd7, 0x9f, 0x82, 0x18, 0xa3, 0x92, 0x59, 0xa7, 0xa2, 0x9a,
            0xab, 0xb2, 0xdb, 0xaf, 0xc3, 0x1c, 0xb3, 0xd3, 0x5d, 0xb7, 0xe3, 0x9e, 0xbb, 0xf3, 0xdf, 0xbf
        ]

        let memo = try MemoBytes(base64URL: s)
        let memoFromBytes = try MemoBytes(bytes: e)

        XCTAssertEqual(memo, memoFromBytes)
        XCTAssertEqual(memo.toBase64URL(), s)
    }
```

**Review by daira — APPROVED** [review]
utACK with suggested additional test.
